openapi: 3.1.0
info:
  title: difluoroborane
  description: FabAccess Machine API
  contact:
    name: dequbed
    email: me@dequbed.space
  license:
    name: GPL-3.0
    identifier: GPL-3.0
  version: 0.4.2
paths:
  /machines:
    get:
      tags: []
      summary: Get machines list
      operationId: list_machines
      responses:
        '200':
          $ref: '#/components/responses/Resources'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
    post:
      tags: []
      summary: Register machine
      operationId: register_machine
      responses:
        '200':
          $ref: '#/components/responses/Machine'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '501':
          description: ''
  /machines/{id}:
    get:
      tags: []
      summary: Get machine
      operationId: get_machine
      parameters:
      - name: id
        in: path
        description: Machine ID
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/Machine'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '404':
          description: ''
    delete:
      tags: []
      summary: Unregister machine
      operationId: unregister_machine
      parameters:
      - name: id
        in: path
        description: Machine ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '404':
          description: ''
        '501':
          description: ''
  /machines/{id}/reservations:
    post:
      tags: []
      summary: Reserve a machine
      operationId: reserve
      parameters:
      - name: id
        in: path
        description: Machine ID
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/Resources'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '404':
          description: ''
  /resources/{id}/reservations:
    get:
      tags: []
      summary: Return reservations for resource
      operationId: get_reservations
      parameters:
      - name: id
        in: path
        description: Machine ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '404':
          description: ''
  /resources/{id}/reservations/latest:
    delete:
      tags: []
      summary: Return latest reservation resource
      operationId: unreserve
      parameters:
      - name: id
        in: path
        description: Machine ID
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/Resources'
        '400':
          description: ''
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: ''
        '404':
          description: ''
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security:
- bearerAuth: []
