openapi: 3.0.3
info:
  title: FabAccess Machine API
  version: 0.0.1
paths:
  /machines:
    get:
      parameters:
      - in: query
        name: page
        schema:
          type: integer
          format: uint64
      summary: Get machine list
      operationId: org.fab-access.machines.list
      responses:
        '200':
          description: Machine list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Machine'
  /machines/{machineId}:
    get:
      summary: Get machine details
      operationId: org.fab-access.machines.get
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machine details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'
        '404':
          description: Machine not found
  /machines/by-urn/{machineUrn}:
    get:
      summary: Get machine by URN
      operationId: org.fab-access.machines.get-urn
      parameters:
        - name: machineUrn
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machine details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'
        '404':
          description: Machine not found

  /machines/{machineId}/properties:
    get:
      summary: Get machine property list
      operationId: org.fab-access.machine.properties.list
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machine property list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineProperties'
        '404':
          description: Machine not found

  /machines/{machineId}/reservations:
    get:
      summary: Get machine reservation list
      operationId: org.fab-access.machine.reservations.list
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machine reservation list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
        '404':
          description: Machine not found

  /machines/{machineId}/use:
    post:
      summary: Use the machine
      operationId: org.fab-access.machine.use
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine usage initiated successfully
        '404':
          description: Machine not found

  /machines/{machineId}/reserve:
    post:
      summary: Reserve the machine
      operationId: org.fab-access.machine.reservations.create
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine reserved successfully
        '404':
          description: Machine not found

  /machines/{machineId}/reserveto:
    post:
      summary: Reserve the machine for a specific time range
      operationId: org.fab-access.machine.reservations.createTo
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
        - name: start
          in: query
          required: true
          schema:
            type: integer
            format: uint64
        - name: end
          in: query
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        '204':
          description: Machine reserved for the specified time range successfully
        '404':
          description: Machine not found

  /machines/{machineId}/giveback:
    post:
      summary: Give back the machine
      operationId: org.fab-access.machine.giveBack
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine given back successfully
        '404':
          description: Machine not found

  /machines/{machineId}/releasefortakeover:
    post:
      summary: Release the machine for takeover
      operationId: org.fab-access.machine.releaseForTakeover
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine released for takeover successfully
        '404':
          description: Machine not found

  /machines/{machineId}/takeover:
    post:
      summary: Take over the machine
      operationId: org.fab-access.machine.takeOverMachine
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine taken over successfully
        '404':
          description: Machine not found

  /machines/{machineId}/check:
    post:
      summary: Check the machine
      operationId: org.fab-access.machine.check
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine checked successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage:
    get:
      summary: Get extended machine info
      operationId: org.fab-access.machine.infoExtended
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Extended machine info retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineInfoExtended'
        '404':
          description: Machine not found

  /machines/{machineId}/manage/properties:
    post:
      summary: Set machine property
      operationId: org.fab-access.machine.properties.set
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Property to be set
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '204':
          description: Machine property set successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/properties/{propertyKey}:
    delete:
      summary: Remove machine property
      operationId: org.fab-access.machine.properties.remove
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
        - name: propertyKey
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine property removed successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/forceuse:
    post:
      summary: Force use the machine
      operationId: org.fab-access.machine.forceUse
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine forced to use successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/forcefree:
    post:
      summary: Force free the machine
      operationId: org.fab-access.machine.forceFree
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine forced to free successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/forcetransfer:
    post:
      summary: Force transfer the machine to another user
      operationId: org.fab-access.machine.forceTransfer
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: User to transfer the machine to
        required: true
        content:
          application/json:
            schema:
              $ref: 'general.yaml#/components/schemas/User'
      responses:
        '204':
          description: Machine forced to transfer successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/block:
    post:
      summary: Block the machine
      operationId: org.fab-access.machine.block
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine blocked successfully
        '404':
          description: Machine not found

  /machines/{machineId}/manage/disable:
    post:
      summary: Disable the machine
      operationId: org.fab-access.machine.disable
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Machine disabled successfully
        '404':
          description: Machine not found

components:
  schemas:
    Machine:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the machine
        space:
          $ref: 'general.yaml#/components/schemas/Space'
        name:
          type: string
          description: The name of the machine
        description:
          type: string
          description: The description of the machine
        state:
          type: string
          enum:
            - free
            - inUse
            - toCheck
            - blocked
            - disabled
            - reserved
            - totakeover
          description: The current state of the machine
        manager:
          $ref: 'general.yaml#/components/schemas/User'
        wiki:
          type: string
          description: The wiki link for the machine
        urn:
          type: string
          description: The URN of the machine
        category:
          type: string
          description: The category of the machine
      required:
        - id
        - space
        - name
        - state
      description: Represents a machine in the system

    MachineInfoExtended:
      type: object
      properties:
        currentUser:
          $ref: 'general.yaml#/components/schemas/User'
        lastUser:
          $ref: 'general.yaml#/components/schemas/User'
        instructorUser:
          $ref: 'general.yaml#/components/schemas/User'
      description: Extended information about a machine

    MachineProperties:
      type: array
      items:
        type: object
        additionalProperties:
          type: string


    Reservation:
      type: object
      properties:
        user:
          $ref: 'general.yaml#/components/schemas/User'
        start:
          type: integer
          format: uint64
          description: The start time of the reservation
        end:
          type: integer
          format: uint64
          description: The end time of the reservation
      required:
        - user
        - start
      description: Represents a reservation for a machine